namespace vmbl.Source.VM;

public interface IVMStackLexer
{
    /// <summary>
    /// Peeks the next character from the source script.
    /// </summary>
    /// 
    /// <param name="cursor">The current value of the cursor</param>
    /// <returns>The character the cursor found</returns>
    /// <seealso cref="IVMStackLexer"/>
    abstract char Peek(int cursor);

    /// <summary>
    /// Main method to instruct which method should be used depending on the current character pointed by the cursor.
    /// </summary>
    /// 
    /// <param name="character">[DEPRECATED] The current character</param>
    /// <param name="cursor">A memory reference to the cursor</param>
    /// <returns>The former Token generated by the respective method</returns>
    /// <seealso cref="Token"/>
    abstract Token LexInstruct(char character, ref int cursor);

    /// <summary>
    /// Main recursive loop that forms the tokenization process.
    /// </summary>
    /// 
    /// <returns>A list of Tokens generated by the recursive loop</returns>
    /// <seealso cref="Token"/>
    abstract List<Token> LexLoop();

    /// <summary>
    /// Lexes a digit, usually ascii-like ones, such as -, =, ; and (
    /// </summary>
    /// 
    /// <param name="character">[DEPRECATED] The current character</param>
    /// <param name="cursor">A memory reference to the cursor</param>
    /// <returns>The former Token with the lexed digit</returns>
    /// <seealso cref="Token"/>
    abstract Token LexDigit(char character, ref int cursor);

    /// <summary>
    /// Lexes an identifier, identifiers are usually words that aren't part of the dictionary of keywords.
    /// </summary>
    /// 
    /// <param name="cursor">A memory reference to the cursor</param>
    /// <returns>The former Token with the lexed identifier</returns>
    /// <seealso cref="Token"/>
    abstract Token LexIdent(ref int cursor);

    /// <summary>
    /// Lexes a string, strings are all values inside quotations.
    /// </summary>
    /// 
    /// <param name="cursor">A memory reference to the cursor</param>
    /// <returns>The former Token with the lexed string</returns>
    /// <seealso cref="Token"/>
    abstract Token LexString(ref int cursor);

    /// <summary>
    /// Lexes a number, the number can be either an integer or a double.
    /// </summary>
    /// 
    /// <param name="cursor">A memory reference to the cursor</param>
    /// <returns>The former Token with the lexed number</returns>
    /// <seealso cref="Token"/>
    abstract Token LexNumber(ref int cursor);

    /// <summary>
    /// Lexes the halt character, always the last token.
    /// </summary>
    /// 
    /// <param name="cursor">A memory reference to the cursor</param>
    /// <returns>The former Token with the lexed halt</returns>
    /// <seealso cref="Token"/>
    [Obsolete("Only useful for the first versions of VMBL, being looked forward for removal.")]
    abstract Token LexHalt(ref int cursor);

    /// <summary>
    /// Adds a single value to the cursor and calls LexInstruct again.
    /// </summary>
    /// 
    /// <param name="cursor">A memory reference to the cursor</param>
    /// <returns>The next Token available</returns>
    /// <seealso cref="Token"/>
    abstract Token LexRecursive(ref int cursor);
}