namespace vmbl.Source.VM;

public interface IVMStackParser
{
    /// <summary>
    /// The next token to be expected.
    /// </summary>
    /// 
    /// <param name="type">The type expected.</param>
    /// <returns>The expected type itself</returns>
    /// <exception cref="Exception">Thrown if the next token is not the same as the one parsed through the parameter</exception>
    /// <seealso cref="IVMStackParser"/>
    abstract TokenTypes Expect(TokenTypes type);

    /// <summary>
    /// The next token to be expected in a list of tokens.
    /// </summary>
    /// 
    /// <param name="types">Types expected.</param>
    /// <returns>The single type that is equal to the next.</returns>
    /// <exception cref="Exception">Thrown if neither element inside the parameters are equal to the next token.</exception>
    /// <seealso cref="IVMStackParser"/>
    abstract TokenTypes ExpectEither(params TokenTypes[] types);

    /// <summary>
    /// Peeks the next full Token.
    /// </summary>
    /// 
    /// <returns>The next Token</returns>
    /// <seealso cref="IVMStackParser"/>
    abstract Token Peek();

    /// <summary>
    /// Parses a single type Value.
    /// </summary>
    /// 
    /// <returns>The value extracted from the Token</returns>
    /// <seealso cref="Value"/>
    abstract Value ParseValues();

    /// <summary>
    /// Parses a single attribute to a type Attribution
    /// </summary>
    /// 
    /// <returns>The attribution mounted with the Values</returns>
    /// <seealso cref="Attribution"/>
    abstract Attribution ParseAttribute();

    /// <summary>
    /// Parses a Statement of type DefineStmt
    /// <para/>
    /// Used for type NODE
    /// </summary>
    /// 
    /// <returns>The Statement of type DefineStmt</returns>
    /// <seealso cref="Statement"/>
    /// <seealso cref="DefineStmt"/>
    abstract Statement ParseDefineNodeStmt();

    /// <summary>
    /// Parses a Statement of type DefineStmt
    /// <para/>
    /// Used for type OBJ
    /// </summary>
    /// 
    /// <returns>The Statement of type DefineStmt</returns>
    /// <seealso cref="Statement"/>
    /// <seealso cref="DefineStmt"/>
    abstract Statement ParseDefineObjStmt();
    
    /// <summary>
    /// Parses a Statement of type QueryStmt
    /// <para/>
    /// Used for all query statements
    /// </summary>
    /// 
    /// <returns>The Statement of type QueryStmt</returns>
    /// <seealso cref="Statement"/>
    /// <seealso cref="QueryStmt"/>
    abstract Statement ParseQueryStmt();

    /// <summary>
    /// The main loop used to parse the Tokens generated by the lexer to an actual AST.
    /// </summary>
    /// 
    /// <param name="token">The next Token of the array</param>
    /// <returns>The Statement generated per Token</returns>
    /// <seealso cref="Statement"/>
    abstract Statement ParseLoop(Token token);

    /// <summary>
    /// The method used to start the recursive parsing process.
    /// <para/>
    /// Happens until the cursor is 0.
    /// </summary>
    /// 
    /// <returns>A list of Statements, or the AST itself.</returns>
    /// <seealso cref="IVMStackParser"/>
    abstract List<Statement> Execute();
}